theme: jekyll-theme-cayman
name: luaphacim site
title: Okay Result
description: > # this means to ignore newlines until "show_excerpts:"
  Sarkari results srkari job.
show_excerpts: false # set to true to show excerpts on the homepage
google_analytics: UA-NNNNNNNN-N
plugins:
 - jekyll-feed
 - jekyll-seo-tag
