theme: jekyll-theme-cayman
title: Show Result
description: > # this means to ignore newlines until "show_excerpts:"
vijay kumar asdfg.

show_excerpts: false # set to true to show excerpts on the homepage
